### ISSUE TITLE
How to enable screen sharing IOS ?

### ISSUE THREAD

**Issue by milzamhibatullah** [driftboat/flutter_zoom#10]
Hi @driftboat 
thanks to create this plugin
but i need to know, is there a way to enable screen sharing on IOS device ?

**Comment by f1forhelp** [comment]
> Hi @driftboat
> thanks to create this plugin
> but i need to know, is there a way to enable screen sharing on IOS device?

It's there, but I think u need to enable it in zoom itself  and also set  `disableShare: false` to false in ZoomMeetingOptions

**Comment by milzamhibatullah** [comment]
> > Hi @driftboat
> > thanks to create this plugin
> > but i need to know, is there a way to enable screen sharing on IOS device?
> 
> It's there, but I think u need to enable it in zoom itself and also set `disableShare: false` to false in ZoomMeetingOptions

yeah i was enable it, but for screen sharing is not available
![WhatsApp Image 2021-09-21 at 10 11 37 AM](https://user-images.githubusercontent.com/17738884/134144951-8b1fbda8-1cab-4e52-a349-4f823575e538.jpeg)

**Comment by driftboat** [comment]
This feature is not supported now. There is a guilde to implement it on iOS：https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/mastering-zoom-sdk/in-meeting-function/screen-share

**Comment by milzamhibatullah** [comment]
> This feature is not supported now. There is a guilde to implement it on iOS：https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/mastering-zoom-sdk/in-meeting-function/screen-share

oh.. i see. thanks for your reply !
