### ISSUE TITLE
Getting error while building code

### ISSUE THREAD

**Issue by GeekySingh** [driftboat/flutter_zoom#11]
Hi, I am using the latest version of zoom (1.0.3). While building project I am getting following error:

```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :commonlib:.
     Searched in the following locations:
       - file:/Users/sam/Documents/Office/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3/android/libs/commonlib.aar
     Required by:
         project :app > project :zoom
   > Could not find :mobilertc:.
     Searched in the following locations:
       - file:/Users/sam/Documents/Office/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3/android/libs/mobilertc.aar
     Required by:
         project :app > project :zoom

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Seems like it is not able to locate `commonlib` and `mobilertc` plugins used by the zoom plugin.

Please guide.

**Comment by driftboat** [comment]
After install the library, must run the follow script to get some sdk stuff for the first time:
`flutter pub run zoom:unzip_zoom_sdk`

**Comment by GeekySingh** [comment]
Thanks for the quick response. This solved the problem.

**Comment by shafiquecbl** [comment]
> After install the library, must run the follow script to get some sdk stuff for the first time: `flutter pub run zoom:unzip_zoom_sdk`

doesn't solve my problem. Still same issue

**Comment by EyMaddis** [comment]
For using it on a real device and **for Simulators on an M1-Chip (ARM) based MacBooks**. you need to use `flutter pub run zoom:unzip_zoom_sdk`.
For simulators of Intel-based Macs, you need to use `flutter pub run zoom:unzip_zoom_sdk dev`

**Comment by shafiquecbl** [comment]
According to documentation i run "flutter pub run flutter_zoom_sdk:unzip_zoom_sdk" but still same issue

**Comment by driftboat** [comment]
Could you show me your console log when using “flutter pub run zoom:unzip_zoom_sdk”，  Please make sure you run the right command "flutter pub run **_zoom_**:unzip_zoom_sdk"，not "flutter pub run **_flutter_zoom_sdk_**:unzip_zoom_sdk"

**Comment by edmirmob** [comment]
> According to documentation i run "flutter pub run flutter_zoom_sdk:unzip_zoom_sdk" but still same issue

did you solve the problem? I have the same issue

**Comment by driftboat** [comment]
flutter pub run zoom:unzip_zoom_sdk
