### ISSUE TITLE
Zoom installation failed for flutter 2.8.0 upgrade

### ISSUE THREAD

**Issue by XenLabsNikhil** [driftboat/flutter_zoom#16]
Facing below issue when upgraded flutter to version 2.8.0 from 2.5.3.
It worked for version 2.5.3

```
$ flutter pub run zoom:unzip_zoom_sdk
Download https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1 to /Users/nikhil/Documents/zoom-trial/.dart_tool/pub/bin/zoom/unzip_zoom_sdk.dart-2.15.0.snapshot/ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/nikhil/Documents/zoom-trial/.dart_tool/pub/bin/zoom/unzip_zoom_sdk.dart-2.15.0.snapshot/ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC' (OS Error: Not a directory, errno = 20)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255
```

**Comment by driftboat** [comment]
Could you download https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1 from webbrowser and copy it to  /Users/nikhil/Documents/zoom-trial/.dart_tool/pub/bin/zoom/ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC ?

**Comment by driftboat** [comment]
Please download it  [https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1](https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1) from webbrowser，then copy it to  `%PUB_CACHE%\hosted\pub.flutter-io\zoom-1.0.3+1\ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/` directory.
[https://www.dropbox.com/s/0qx52d1cb45oxku/MobileRTC?dl=1](https://www.dropbox.com/s/0qx52d1cb45oxku/MobileRTC?dl=1) to
`%PUB_CACHE%\Pub\Cache\hosted\pub.flutter-io\zoom-1.0.3+1\ios/MobileRTC.xcframework/ios-i386_x86_64-simulator/MobileRTC.framework/`
[https://www.dropbox.com/s/lcjoc2evrmeucte/commonlib.aar?dl=1](https://www.dropbox.com/s/lcjoc2evrmeucte/commonlib.aar?dl=1)  and [https://www.dropbox.com/s/exe1aa0aflyh53f/mobilertc.aar?dl=1](https://www.dropbox.com/s/exe1aa0aflyh53f/mobilertc.aar?dl=1) to
 `%PUB_CACHE%\Pub\Cache\hosted\pub.flutter-io\zoom-1.0.3+1\android\libs\` 
%PUB_CACHE% is https://dart.dev/tools/pub/environment-variables

**Comment by driftboat** [comment]
It seems that this script executed by a snapshot ，so `Platform.script` get a wrong path to that snapshot

**Comment by driftboat** [comment]
1.0.3+2 has been published for fixing the issue

**Comment by XenLabsNikhil** [comment]
> 1.0.3+2 has been published for fixing the issue

Tried this one. But got below error for android library - 

```
$ flutter pub run zoom:unzip_zoom_sdk
Download https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1 to /Users/xenlabs/Documents/Nikhil/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+2/ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC
Download https://www.dropbox.com/s/0qx52d1cb45oxku/MobileRTC?dl=1 to /Users/xenlabs/Documents/Nikhil/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+2/ios/MobileRTC.xcframework/ios-i386_x86_64-simulator/MobileRTC.framework/MobileRTC
Download https://www.dropbox.com/s/lcjoc2evrmeucte/commonlib.aar?dl=1 to /Users/xenlabs/Documents/Nikhil/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+2/android/libs/commonlib.aar
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/xenlabs/Documents/Nikhil/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+2/android/libs/commonlib.aar' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255

```

**Comment by XenLabsNikhil** [comment]
Identified the problem. 

After `flutter pub get` observed that `libs` directory is missing in `.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+2/android/` directory.

You might have to create that directory in script if not present already.

Thanks.

**Comment by XenLabsNikhil** [comment]
Created pull request #17 for this. 
Please review.

**Comment by driftboat** [comment]
There is a ".gitkeep" file under that directory ,It should be there, I will check it

**Comment by driftboat** [comment]
Thanks! 1.0.3+3  has been published

**Comment by XenLabsNikhil** [comment]
> Thanks! 1.0.3+3 has been published

Great. Thanks. 

Closing this.
