### ISSUE TITLE
Existing app size increase issue.

### ISSUE THREAD

**Issue by ZohanTesting** [driftboat/flutter_zoom#18]
After implementing it my app size increase to 147MB from 27MB. Is there anything I can do to reduce the app size?

**Comment by driftboat** [comment]
https://devforum.zoom.us/t/apk-size-after-adding-android-zoom-sdk/16573/5

**Comment by ZohanTesting** [comment]
Sorry for the late reply. I have already found a solution. But thanks for the links. It also helps a lot.

**Comment by sahhill** [comment]
Hi @ZohanTesting can you tell what change did you make?

**Comment by ZohanTesting** [comment]
Use the following command @[sahhill](https://github.com/sahhill)

flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
