### ISSUE TITLE
Blank Screen and no response

### ISSUE THREAD

**Issue by devianl2** [driftboat/flutter_zoom#2]
Hi, I am receiving "old data has cpoied done" message from this library. I am running in iOS environment with following commands but still receive the same error:

flutter pub run zoom:unzip_zoom_sdk dev

flutter pub run zoom:unzip_zoom_sdk

**Comment by driftboat** [comment]
Please make sure your jwtToken is correct and the zoom room setting  allow anyone to join 
1. Disable "Only users admitted by the host can join the meeting" under the "Waiting Room"
2. Enable  "Allow participants to join anytime" in the "Meeting Options"

**Comment by devianl2** [comment]
> Please make sure your jwtToken is correct and the zoom room setting allow anyone to join
> 
> 1. Disable "Only users admitted by the host can join the meeting" under the "Waiting Room"
> 2. Enable  "Allow participants to join anytime" in the "Meeting Options"

Followed with above settings and generated JWT token but received status message:

old data has cpoied done

**Comment by driftboat** [comment]
Could you show me all  messages  in the "DEBUG CONSOLE", and you can check these bellow:
1. Make sure create jwtToken following this guild: https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#example
2. You can check your auth result in the join_screen.dart , zero means success, others mean fail `zoom.init(zoomOptions).then((results) {
      if (results[0] == 0) {`

**Comment by devianl2** [comment]
> Could you show me all messages in the "DEBUG CONSOLE", and you can check these bellow:
> 
> 1. Make sure create jwtToken following this guild: https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#example
> 2. You can check your auth result in the join_screen.dart , zero means success, others mean fail `zoom.init(zoomOptions).then((results) { if (results[0] == 0) {`

I've follow exactly steps to generate token in jwt.io with PAYLOAD :
{
  "appKey": "My Key",
  "exp": 1624935628,
  "iat": 1624888028,
  "tokenExp": 6400
}

HMACSHA256(
  base64UrlEncode(header) + "." +
  base64UrlEncode(payload),
  My Secret
)



This is my code:
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Loading Zoom Training '),
      ),
      body: Padding(
          padding: EdgeInsets.all(16.0),
          child: Builder(
            builder: (context) {
              // The basic Material Design action button.
              return RaisedButton(
                // If onPressed is null, the button is disabled
                // this is my goto temporary callback.
                onPressed: () => joinMeeting(context),
                child: Text('Join'),
              );
            },
          )
      ),
    );
  }

  bool _isMeetingEnded(String status) {
    var result = false;

    if (Platform.isAndroid) {
      result = status == "MEETING_STATUS_DISCONNECTING" || status == "MEETING_STATUS_FAILED";
    } else {
      result = status == "MEETING_STATUS_IDLE";
    }

    return result;
  }

  bool _isInMeeting(String status) {
    if (status == "MEETING_STATUS_INMEETING") {
      return true;
    } else {
      return false;
    }
  }

  joinMeeting(BuildContext context) {

    ZoomOptions zoomOptions = new ZoomOptions(
      domain: "zoom.us",
      //https://marketplace.zoom.us/docs/sdk/native-sdks/auth
      //https://jwt.io/
      //--todo from server
      jwtToken: "generated JWT Token,
    );
    var meetingOptions = new ZoomMeetingOptions(
        userId: 'randomUser',
        displayName: 'randomUser',
        meetingId: 'meetingId',
        meetingPassword: 'meetingPassword',
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "true",
        disableShare: "true",
        noAudio: "false",
        noDisconnectAudio: "false");

    var zoom = Zoom();
    zoom.init(zoomOptions).then((results) {
      if (results[0] == 0) {
        zoom.onMeetingStateChanged.listen((status) {
          print("Meeting Status Stream: " + status[0] + " - " + status[1]);
          if (_isMeetingEnded(status[0])) {
            timer?.cancel();
          }
        });
        zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
          timer = Timer.periodic(new Duration(seconds: 2), (timer) {
            zoom.meetingStatus(meetingOptions.meetingId).then((status) {
              print("Meeting Status Polling: " + status[0] + " - " + status[1]);
            });
          });
        });
      }
    });


Response in console:
[GETX] GOING TO ROUTE /zoom_page
[GETX] Instance "ZoomController" has been created
[GETX] Instance "ZoomController" has been initialized
old data has cpoied done

**Comment by devianl2** [comment]
I've done the following:

**Pod File:**
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

SDK Command:
flutter pub run zoom:unzip_zoom_sdk

Info.plist:
<key>NSCameraUsageDescription</key>
<string>Need to use the camera for call</string>
<key>NSMicrophoneUsageDescription</key>
<string>Need to use the microphone for call</string>

**Comment by driftboat** [comment]
The tokenExp in your payload is invalid, tokenExp should be timestamp, you can see the "PAYLOAD Example" :
`{
  "appKey": "xxxxxxxxxxxxxxxxxxxx", 
  "iat": 1615510799, 
  "exp": 1647017999, 
  "tokenExp": 1647017999 
}
 `

 https://devforum.zoom.us/t/sdk-jwt-token-fail/25422/4
1). The exp should be later than tokenExp
2). tokenExp should be a timestamp that is at least 30 minutes later than the iat

Please try to make exp larger (1 day later) and see if that helps.

**Comment by uzirthapa** [comment]
Just adding the JWT in the example doesnt seem to solve the issue. I extended the jwt time to expire in a day. but still not working. 

I am getting jwt from zoom marketplace and created an app.

**Comment by driftboat** [comment]
Did you generate the "jwt token" from "jwt.io"? It should look like this(Please ensure you are copying the key and secret for an SDK app on the marketplace.):

![image](https://user-images.githubusercontent.com/247809/133621832-52b4782d-767b-446b-9e3b-9d17117e6298.png)

**Comment by driftboat** [comment]
<img width="377" alt="截屏2021-09-16 下午9 42 00" src="https://user-images.githubusercontent.com/247809/133623607-2c6fb078-3ace-4416-b59c-ecc1190a18fe.png">

**Comment by uzirthapa** [comment]
Ah I understand what you are saying now, Gonna try it with this and let you know. Thank you!

**Comment by uzirthapa** [comment]
Ok, I tried it and I'm still getting the same error. I have attached the image of the jwt.io screen, vscode and zoom SDK credentials screen

![Screen Shot 2021-09-16 at 9 08 11 AM](https://user-images.githubusercontent.com/20262159/133627516-7a519da5-8ae8-487e-90c9-a99bfa5b3d3d.png)

![Screen Shot 2021-09-16 at 9 11 03 AM](https://user-images.githubusercontent.com/20262159/133627616-6a5238b3-c233-4e08-8590-363fb1c36724.png)

![Screen Shot 2021-09-16 at 9 11 49 AM](https://user-images.githubusercontent.com/20262159/133627787-ae1e7594-f84a-4584-bb18-27793306153e.png)

**Comment by driftboat** [comment]
The timestamps should be in seconds(https://www.unixtimestamp.com/) ,It is 10 digits, example:
`{
  "appKey": "xxxxxxxxxxxxxxxxxxxx", 
  "iat": 1615510799, 
  "exp": 1647017999, 
  "tokenExp": 1647017999 
}`

**Comment by uzirthapa** [comment]
This plugin works better I think. Easier to setup. If you want to use ios just change to dev branch. 

https://github.com/evilrat/flutter_zoom_sdk

**Comment by driftboat** [comment]
ZoomSDKInitParams will include your access credentials for authentication, and can be either a JWT or SDK Key & Secret. I think use JWT token from your server is safe, So I remove  "SDK Key & Secret" from ZoomOptions , I will add them back :)

**Comment by sadaqatdev** [comment]
please add  "SDK Key & Secret" or jwt as optional for user

**Comment by uzirthapa** [comment]
> ZoomSDKInitParams will include your access credentials for authentication, and can be either a JWT or SDK Key & Secret. I think use JWT token from your server is safe, So I remove "SDK Key & Secret" from ZoomOptions , I will add them back :)

Yeah, I see how you are thinking, and I think that would be good. I think we should leave that up to the user how they want to implement. Maybe another way to do it would be to decode the JWT on the app and then use the appKey and appSecret from there.

**Comment by driftboat** [comment]
Thanks for your suggestion, flutter_zoom 1.0.2+3 And 1.0.3 add them back.
