### ISSUE TITLE
Published version on pub.dev does not include native code

### ISSUE THREAD

**Issue by EyMaddis** [driftboat/flutter_zoom#3]
Hi,
thanks for updating the plugin. 
I wanted to let you know that the version on [pub.dev](https://pub.dev/packages/zoom) does not contain `android/`, `ios/` and  `ios-sdk/` and is therefore not usable directly.

**Comment by driftboat** [comment]
Package that publish to pub.dev must be less than 100 MB large after gzip compression , for now I have no idea to deal with the limit [https://dart.dev/tools/pub/publishing#preparing-to-publish](https://dart.dev/tools/pub/publishing#preparing-to-publish)

**Comment by EyMaddis** [comment]
You can download this via the `flutter pub run zoom:unzip_zoom_sdk`
https://devforum.zoom.us/t/how-to-download-mobilertc-all-sdk-zip-for-ios-via-curl/9760

**Comment by driftboat** [comment]
Thanks! I will try

**Comment by driftboat** [comment]
The version 1.0.2 on  [pub.dev](https://pub.dev/packages/zoom) download the sdk stuff from github repository when run the  `flutter pub run zoom:unzip_zoom_sdk `
