### ISSUE TITLE
zoom init not working

### ISSUE THREAD

**Issue by iamgouravturka** [driftboat/flutter_zoom#4]
showing results [1, 0]...
tried on emulator and android device (one plus nord)

**Comment by driftboat** [comment]
The error code "1" means https://zoom.github.io/zoom-sdk-android/constant-values.html#us.zoom.sdk.ZoomError.ZOOM_ERROR_INVALID_ARGUMENTS.
Please make sure you have replaced the "your jwtToken" following this guild: https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#example
