### ISSUE TITLE
Installation problem , after running the command  ( flutter pub run zoom:unzip_zoom_sdk the following error occur  )

### ISSUE THREAD

**Issue by sadaqatdev** [driftboat/flutter_zoom#5]
apple@Apples-iMac zoom_test % flutter pub run zoom:unzip_zoom_sdk

Download https://raw.githubusercontent.com/driftboat/flutter_zoom/1.0.1/zoom/ios-sdk/MobileRTC.zip to /Users/apple/Documents/flutter_data/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.2+1/ios-sdk/MobileRTC.zip

Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/apple/Documents/flutter_data/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.2+1/ios-sdk/MobileRTC.zip' (OS Error: No such file or directory, errno = 2)

#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255

**Comment by driftboat** [comment]
Do you have the zoom-1.0.2+1 (or zoom-1.0.x) directory under /Users/apple/Documents/flutter_data/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/  ?

**Comment by driftboat** [comment]
Please create the "ios-sdk" directory under /Users/apple/Documents/flutter_data/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.2+1/ and "libs" directory under  /Users/apple/Documents/flutter_data/flutter_sdk/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.2+1/android

**Comment by driftboat** [comment]
I have published zoom-1.0.2+2, Please update to the new version and try again

**Comment by sadaqatdev** [comment]
ok, i will try

**Comment by sadaqatdev** [comment]
it working thank you.

**Comment by XenLabsNikhil** [comment]
Facing same issue when upgraded flutter to version 2.8.0 from 2.5.3

```
$ flutter pub run zoom:unzip_zoom_sdk
Download https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1 to /Users/nikhil/Documents/zoom-trial/.dart_tool/pub/bin/zoom/unzip_zoom_sdk.dart-2.15.0.snapshot/ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/nikhil/Documents/zoom-trial/.dart_tool/pub/bin/zoom/unzip_zoom_sdk.dart-2.15.0.snapshot/ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC' (OS Error: Not a directory, errno = 20)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
pub finished with exit code 255
```
