### ISSUE TITLE
Not running in ios, please review 

### ISSUE THREAD

**Issue by sadaqatdev** [driftboat/flutter_zoom#6]
Showing Recent Issues
Undefined symbol: _OBJC_CLASS_$_MobileRTCSDKInitContext

Undefined symbol: _OBJC_CLASS_$_MobileRTC

Undefined symbol: _kMeetingParam_MeetingPassword

Undefined symbol: _kMeetingParam_Username

Undefined symbol: _OBJC_CLASS_$_MobileRTCMeetingStartParam4WithoutLoginUser

Undefined symbol: _kMeetingParam_MeetingNumber

**Comment by driftboat** [comment]
Please check "NOTE for testing on the iOS simulator" in https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#ios
On  iOS Simulator, Please run `flutter pub run zoom:unzip_zoom_sdk dev` to get " iOS Dev Zoom SDK "

**Comment by sadaqatdev** [comment]
> Please check "NOTE for testing on the iOS simulator" in https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#ios
> On iOS Simulator, Please run `flutter pub run zoom:unzip_zoom_sdk dev` to get " iOS Dev Zoom SDK 

thanks its working

**Comment by sadaqatdev** [comment]
failed to initialised zoom sdk

**Comment by driftboat** [comment]
Please make sure you have replaced the "your jwtToken" following this guild: https://github.com/driftboat/flutter_zoom/blob/main/zoom/README.md#example

**Comment by driftboat** [comment]
Duplicate of #2
